---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name}}-redash-cfg
data:
  POSTGRES_PASSWORD: insecure
  PYTHONUNBUFFERED: "0"
  REDASH_DATABASE_URL: postgresql://postgres:insecure@localhost/postgres
  REDASH_LOG_LEVEL: INFO