apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name}}-pg-airflow-exporter"
spec:
  ports:
  - name: http-metrics
    port: 9187
    nodePort: 32001
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/name: postgresql
    role: primary
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
