apiVersion: v1
kind: Service
metadata:   
  name: "{{ .Release.Name}}-statsd-expose"
spec:
  ports:
  - name: statsd
    nodePort: 32000
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector: 
    component: statsd
    release: {{ .Release.Name}}
    tier: airflow
  sessionAffinity: None
  type: NodePort