apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-default-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name}}-role-all
subjects:
- namespace: {{ .Release.Namespace}} 
  kind: ServiceAccount
  name: {{ .Release.Name}}-airflow-worker 
- namespace: {{ .Release.Namespace}}  
  kind: ServiceAccount
  name: default