{{- if and .Values.hue.database.persist .Values.hue.database.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: {{ .Values.hue.database.storageName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hue.database.storageCapacity }}
{{- end -}}
