apiVersion: v1
kind: Service
metadata:
  name: hue
  labels:
    pod: hue
spec:
  selector:
    pod: hue
  ports:
  - name: hue
    port: 8888
    nodePort: {{ .Values.hue.service.nodePort }}
  type: NodePort
