apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-trino-svc
  namespace: {{ .Release.Namespace}}
  labels: 
    app: trino-coordinator
spec:
  type: {{ .Values.service.type}}
  ports:
   - port: {{ .Values.service.port}}
     targetPort: 8080
     {{- if eq .Values.service.type "NodePort"}}
     nodePort: {{ .Values.service.nodeport}}
     {{- end}}
  selector:
    app: trino-coordinator
  
