apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name}}-hive-initschema
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-failed, hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: hivemetastore
          image: {{ .Values.image.repository}}                    #gcr.io/project-yasmine/hivemetastore:2.0
          command: [{{  .Values.binDirectory}}/bin/schematool]                 #["/opt/apache-hive-metastore-3.0.0-bin/bin/schematool"]
          args: ["--verbose" ,"-initSchema" , "-dbType", "postgres" , "-driver", "org.postgresql.Driver", "-userName", "{{ .Values.pg.access.user}}", 
            "-passWord", "{{ .Values.pg.access.password}}" , "-url", "jdbc:postgresql://{{ .Release.Name }}-{{ .Values.pg.component}}-pg-service:{{ .Values.pg.access.port}}/{{ .Values.pg.access.database}}?createDatabaseIfNotExist=true&connectTimeout=2000"]
      restartPolicy: Never
  backoffLimit: 20
