apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-pg-metastore-svc
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
     targetPort: 5432
  selector:
   app: postgres
---