kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name}}-pg-metastore-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi